app = "tax-assist"
primary_region = "nrt"

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "1"
  RAILS_MAX_THREADS = "3"
  WEB_CONCURRENCY = "0"
  RAILS_SERVE_STATIC_FILES = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[deploy]
   release_command = "bash -lc 'RAILS_ENV=production bin/rails db:seed'"